apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
         - name: con1
           image: prajwalp01/portfolio:v1
           ports:
            - containerPort: 3000
